language: cpp

os: osx

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX_=g++-5 CC_=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX_=clang++-3.8 CC_=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

before_script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      PWD=`pwd`
      export PATH=${PWD}/cmake/bin:${PATH}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi

script: ./.travis.sh

branches:
  only:
  - master
