// Copyright (c) 2017 Philip Herron.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

/* Header for class com_github_redbrain_overflow_RtspClient */

#ifndef _Included_com_github_redbrain_overflow_RtspClient
#define _Included_com_github_redbrain_overflow_RtspClient

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_redbrain_overflow_RtspClient
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_github_redbrain_overflow_RtspClient__1Start
        (JNIEnv *, jobject);

/*
 * Class:     com_github_redbrain_overflow_RtspClient
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_redbrain_overflow_RtspClient_Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_github_redbrain_overflow_RtspClient
 * Method:    _new_client
 * Signature: (Lcom/github/redbrain/overflow/RtspClientDelegate;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_redbrain_overflow_RtspClient__1new_1client
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_github_redbrain_overflow_RtspClient
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_redbrain_overflow_RtspClient_Close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
